server:
  port: 8080

spring:
  application:
    name: other-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      routes:
        - id: presale
          uri: http://localhost:8988/
          predicates:
            - Path=/presales/states,/presales,/shops/{shopId}/spus/{id}/presales,/shops/{shopId}/presales/{id}
          filters:
            - PrefixPath=/presale

        - id: shop
          uri: http://localhost:8907/
          predicates:
            - Path=/shops/states,/shops,/shops/{id},/shops/{shopId}/newshops/{id}/audit,/shops/{id}/onshelves,/shops/{id}/offshelves
          filters:
            - PrefixPath=/shop

        - id: falshsale
          uri: http://localhost:8188/
          predicates:
            - Path=/timesegments/{id}/flashsales,/flashsales/current,/flashsales/{id},/flashsales/{id}/flashitems,/flashsales/{fid}/flashitems/{id}
          filters:
            - PrefixPath=/flashsale

        - id: coupon
          uri: http://localhost:8988/
          predicates:
            - Path=/coupons/states,/shops/{shopId}/couponactivities,/shops/{shopId}/couponactivities/{id}/uploadImg,/couponactivities,/shops/{id}/couponactivities/invalid,/couponactivities/{id}/skus,/shops/{shopId}/couponactivities/{id},/shops/{shopId}/couponactivities/{id}/skus,/shops/{shopId}/couponskus/{id},/coupons,/couponactivities/{id}/usercoupons,/shops/{shopId}/couponactivities/{id}/onshelves,/shops/{shopId}/couponactivities/{id}/offshelves
          filters:
            - PrefixPath=/coupon

        - id: groupon
          uri: http://localhost:8988/
          predicates:
            - Path=/groupons/states,/groupons,/shops/{id}/groupons,/shops/{shopId}/spus/{id}/groupons,/shops/{shopId}/groupons/{id},/shops/{shopId}/groupons/{id}/onshelves,/shops/{shopId}/groupons/{id}/offshelves
          filters:
            - PrefixPath=/groupon

        - id: login
          uri: http://localhost:8081/
          predicates:
            - Path=/adminusers,/privileges/login
          filters:
            - PrefixPath=/privilege

        - id: goods
          uri: http://localhost:8907/
          predicates:
            - Path=/skus/states,/skus,/brands,/shops/{shopId}/brands/**,/skus/**,/spus/**,/shops/{shopId}/floatPrices/**,/shops/{shopId}/spus/**,/shops/{shopId}/skus/**,/categories/{id}/subcategories,/shops/{shopId}/categories/**
          filters:
            - PrefixPath=/goods

        - id: adminusers
          uri: http://localhost:8081/
          predicates:
            - Path=/adminusers/**,/shops/{shopid}/adminusers/**,/proxies/**,/shops/{shopid}/proxies/**,/shops/{shopid}/roles/**,/shops/{shopid}/roleprivileges/**,/privileges/**,/roles/**,/roles,/shops/{shopid}/roles
          filters:
            - PrefixPath=/privilege
            - Auth=authorization


#        - id: adminusers
#          uri: http://localhost:9999/
#          predicates:
#            - Path=/users
#            - Method=GET
#          filters:
#            - Auth=authorization
management:
  endpoint:
    gateway:
      enabled: true