server:
  port: 8080

spring:
  application:
    name: other-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      routes:
        - id: presale
          uri: http://localhost:8988/
          predicates:
            - Path=/presales/states,/presales,/shops/{shopId}/spus/{id}/presales,/shops/{shopId}/presales/{id}
          filters:
            - PrefixPath=/presale

        - id: shop
          uri: http://localhost:8907/
          predicates:
            - Path=/shops/states,/shops,/shops/{id},/shops/{shopId}/newshops/{id}/audit,/shops/{id}/onshelves,/shops/{id}/offshelves
          filters:
            - PrefixPath=/shop

        - id: falshsale
          uri: http://localhost:8188/
          predicates:
            - Path=/timesegments/{id}/flashsales,/flashsales/current,/flashsales/{id},/flashsales/{id}/flashitems,/flashsales/{fid}/flashitems/{id}
          filters:
            - PrefixPath=/flashsale


#        - id: adminusers
#          uri: http://localhost:9999/
#          predicates:
#            - Path=/users
#            - Method=GET
#          filters:
#            - Auth=authorization
management:
  endpoint:
    gateway:
      enabled: true